spring:
  application:
    name: tns-capital-api
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/tns_capital}
    username: ${SPRING_DATASOURCE_USERNAME:tns-capital-db-user}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

mybatis:
  type-aliases-package: com.neueda.leap.model
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 3000

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /v3/api-docs